// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InfractionSefvice.proto

package ma.infractionservice.web.grpc.stub;

public final class InfractionSefvice {
  private InfractionSefvice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InfractionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InfractionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double montant = 1;</code>
     * @return The montant.
     */
    double getMontant();

    /**
     * <code>string date = 2;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 2;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>int64 nuneroRadar = 3;</code>
     * @return The nuneroRadar.
     */
    long getNuneroRadar();

    /**
     * <code>string matriculeVehicule = 4;</code>
     * @return The matriculeVehicule.
     */
    java.lang.String getMatriculeVehicule();
    /**
     * <code>string matriculeVehicule = 4;</code>
     * @return The bytes for matriculeVehicule.
     */
    com.google.protobuf.ByteString
        getMatriculeVehiculeBytes();

    /**
     * <code>double vitesseMax = 5;</code>
     * @return The vitesseMax.
     */
    double getVitesseMax();
  }
  /**
   * Protobuf type {@code InfractionRequest}
   */
  public  static final class InfractionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InfractionRequest)
      InfractionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InfractionRequest.newBuilder() to construct.
    private InfractionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InfractionRequest() {
      date_ = "";
      matriculeVehicule_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InfractionRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InfractionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              montant_ = input.readDouble();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 24: {

              nuneroRadar_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              matriculeVehicule_ = s;
              break;
            }
            case 41: {

              vitesseMax_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest.class, ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest.Builder.class);
    }

    public static final int MONTANT_FIELD_NUMBER = 1;
    private double montant_;
    /**
     * <code>double montant = 1;</code>
     * @return The montant.
     */
    public double getMontant() {
      return montant_;
    }

    public static final int DATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 2;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 2;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUNERORADAR_FIELD_NUMBER = 3;
    private long nuneroRadar_;
    /**
     * <code>int64 nuneroRadar = 3;</code>
     * @return The nuneroRadar.
     */
    public long getNuneroRadar() {
      return nuneroRadar_;
    }

    public static final int MATRICULEVEHICULE_FIELD_NUMBER = 4;
    private volatile java.lang.Object matriculeVehicule_;
    /**
     * <code>string matriculeVehicule = 4;</code>
     * @return The matriculeVehicule.
     */
    public java.lang.String getMatriculeVehicule() {
      java.lang.Object ref = matriculeVehicule_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matriculeVehicule_ = s;
        return s;
      }
    }
    /**
     * <code>string matriculeVehicule = 4;</code>
     * @return The bytes for matriculeVehicule.
     */
    public com.google.protobuf.ByteString
        getMatriculeVehiculeBytes() {
      java.lang.Object ref = matriculeVehicule_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matriculeVehicule_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VITESSEMAX_FIELD_NUMBER = 5;
    private double vitesseMax_;
    /**
     * <code>double vitesseMax = 5;</code>
     * @return The vitesseMax.
     */
    public double getVitesseMax() {
      return vitesseMax_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (montant_ != 0D) {
        output.writeDouble(1, montant_);
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, date_);
      }
      if (nuneroRadar_ != 0L) {
        output.writeInt64(3, nuneroRadar_);
      }
      if (!getMatriculeVehiculeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, matriculeVehicule_);
      }
      if (vitesseMax_ != 0D) {
        output.writeDouble(5, vitesseMax_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (montant_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, montant_);
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, date_);
      }
      if (nuneroRadar_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, nuneroRadar_);
      }
      if (!getMatriculeVehiculeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, matriculeVehicule_);
      }
      if (vitesseMax_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, vitesseMax_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest)) {
        return super.equals(obj);
      }
      ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest other = (ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest) obj;

      if (java.lang.Double.doubleToLongBits(getMontant())
          != java.lang.Double.doubleToLongBits(
              other.getMontant())) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (getNuneroRadar()
          != other.getNuneroRadar()) return false;
      if (!getMatriculeVehicule()
          .equals(other.getMatriculeVehicule())) return false;
      if (java.lang.Double.doubleToLongBits(getVitesseMax())
          != java.lang.Double.doubleToLongBits(
              other.getVitesseMax())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MONTANT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMontant()));
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + NUNERORADAR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNuneroRadar());
      hash = (37 * hash) + MATRICULEVEHICULE_FIELD_NUMBER;
      hash = (53 * hash) + getMatriculeVehicule().hashCode();
      hash = (37 * hash) + VITESSEMAX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVitesseMax()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InfractionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InfractionRequest)
        ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest.class, ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest.Builder.class);
      }

      // Construct using ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        montant_ = 0D;

        date_ = "";

        nuneroRadar_ = 0L;

        matriculeVehicule_ = "";

        vitesseMax_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionRequest_descriptor;
      }

      @java.lang.Override
      public ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest getDefaultInstanceForType() {
        return ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest build() {
        ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest buildPartial() {
        ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest result = new ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest(this);
        result.montant_ = montant_;
        result.date_ = date_;
        result.nuneroRadar_ = nuneroRadar_;
        result.matriculeVehicule_ = matriculeVehicule_;
        result.vitesseMax_ = vitesseMax_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest) {
          return mergeFrom((ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest other) {
        if (other == ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest.getDefaultInstance()) return this;
        if (other.getMontant() != 0D) {
          setMontant(other.getMontant());
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (other.getNuneroRadar() != 0L) {
          setNuneroRadar(other.getNuneroRadar());
        }
        if (!other.getMatriculeVehicule().isEmpty()) {
          matriculeVehicule_ = other.matriculeVehicule_;
          onChanged();
        }
        if (other.getVitesseMax() != 0D) {
          setVitesseMax(other.getVitesseMax());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double montant_ ;
      /**
       * <code>double montant = 1;</code>
       * @return The montant.
       */
      public double getMontant() {
        return montant_;
      }
      /**
       * <code>double montant = 1;</code>
       * @param value The montant to set.
       * @return This builder for chaining.
       */
      public Builder setMontant(double value) {
        
        montant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double montant = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMontant() {
        
        montant_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 2;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private long nuneroRadar_ ;
      /**
       * <code>int64 nuneroRadar = 3;</code>
       * @return The nuneroRadar.
       */
      public long getNuneroRadar() {
        return nuneroRadar_;
      }
      /**
       * <code>int64 nuneroRadar = 3;</code>
       * @param value The nuneroRadar to set.
       * @return This builder for chaining.
       */
      public Builder setNuneroRadar(long value) {
        
        nuneroRadar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 nuneroRadar = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNuneroRadar() {
        
        nuneroRadar_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object matriculeVehicule_ = "";
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @return The matriculeVehicule.
       */
      public java.lang.String getMatriculeVehicule() {
        java.lang.Object ref = matriculeVehicule_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matriculeVehicule_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @return The bytes for matriculeVehicule.
       */
      public com.google.protobuf.ByteString
          getMatriculeVehiculeBytes() {
        java.lang.Object ref = matriculeVehicule_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matriculeVehicule_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @param value The matriculeVehicule to set.
       * @return This builder for chaining.
       */
      public Builder setMatriculeVehicule(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        matriculeVehicule_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMatriculeVehicule() {
        
        matriculeVehicule_ = getDefaultInstance().getMatriculeVehicule();
        onChanged();
        return this;
      }
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @param value The bytes for matriculeVehicule to set.
       * @return This builder for chaining.
       */
      public Builder setMatriculeVehiculeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        matriculeVehicule_ = value;
        onChanged();
        return this;
      }

      private double vitesseMax_ ;
      /**
       * <code>double vitesseMax = 5;</code>
       * @return The vitesseMax.
       */
      public double getVitesseMax() {
        return vitesseMax_;
      }
      /**
       * <code>double vitesseMax = 5;</code>
       * @param value The vitesseMax to set.
       * @return This builder for chaining.
       */
      public Builder setVitesseMax(double value) {
        
        vitesseMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double vitesseMax = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVitesseMax() {
        
        vitesseMax_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InfractionRequest)
    }

    // @@protoc_insertion_point(class_scope:InfractionRequest)
    private static final ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest();
    }

    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InfractionRequest>
        PARSER = new com.google.protobuf.AbstractParser<InfractionRequest>() {
      @java.lang.Override
      public InfractionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InfractionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InfractionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InfractionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InfractionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:InfractionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string date = 2;</code>
     * @return The date.
     */
    java.lang.String getDate();
    /**
     * <code>string date = 2;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();

    /**
     * <code>int64 nuneroRadar = 3;</code>
     * @return The nuneroRadar.
     */
    long getNuneroRadar();

    /**
     * <code>string matriculeVehicule = 4;</code>
     * @return The matriculeVehicule.
     */
    java.lang.String getMatriculeVehicule();
    /**
     * <code>string matriculeVehicule = 4;</code>
     * @return The bytes for matriculeVehicule.
     */
    com.google.protobuf.ByteString
        getMatriculeVehiculeBytes();

    /**
     * <code>double vitesseMax = 5;</code>
     * @return The vitesseMax.
     */
    double getVitesseMax();

    /**
     * <code>double montant = 6;</code>
     * @return The montant.
     */
    double getMontant();
  }
  /**
   * Protobuf type {@code InfractionResponse}
   */
  public  static final class InfractionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:InfractionResponse)
      InfractionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InfractionResponse.newBuilder() to construct.
    private InfractionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InfractionResponse() {
      date_ = "";
      matriculeVehicule_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InfractionResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InfractionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
            case 24: {

              nuneroRadar_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              matriculeVehicule_ = s;
              break;
            }
            case 41: {

              vitesseMax_ = input.readDouble();
              break;
            }
            case 49: {

              montant_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse.class, ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int DATE_FIELD_NUMBER = 2;
    private volatile java.lang.Object date_;
    /**
     * <code>string date = 2;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>string date = 2;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUNERORADAR_FIELD_NUMBER = 3;
    private long nuneroRadar_;
    /**
     * <code>int64 nuneroRadar = 3;</code>
     * @return The nuneroRadar.
     */
    public long getNuneroRadar() {
      return nuneroRadar_;
    }

    public static final int MATRICULEVEHICULE_FIELD_NUMBER = 4;
    private volatile java.lang.Object matriculeVehicule_;
    /**
     * <code>string matriculeVehicule = 4;</code>
     * @return The matriculeVehicule.
     */
    public java.lang.String getMatriculeVehicule() {
      java.lang.Object ref = matriculeVehicule_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matriculeVehicule_ = s;
        return s;
      }
    }
    /**
     * <code>string matriculeVehicule = 4;</code>
     * @return The bytes for matriculeVehicule.
     */
    public com.google.protobuf.ByteString
        getMatriculeVehiculeBytes() {
      java.lang.Object ref = matriculeVehicule_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matriculeVehicule_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VITESSEMAX_FIELD_NUMBER = 5;
    private double vitesseMax_;
    /**
     * <code>double vitesseMax = 5;</code>
     * @return The vitesseMax.
     */
    public double getVitesseMax() {
      return vitesseMax_;
    }

    public static final int MONTANT_FIELD_NUMBER = 6;
    private double montant_;
    /**
     * <code>double montant = 6;</code>
     * @return The montant.
     */
    public double getMontant() {
      return montant_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, date_);
      }
      if (nuneroRadar_ != 0L) {
        output.writeInt64(3, nuneroRadar_);
      }
      if (!getMatriculeVehiculeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, matriculeVehicule_);
      }
      if (vitesseMax_ != 0D) {
        output.writeDouble(5, vitesseMax_);
      }
      if (montant_ != 0D) {
        output.writeDouble(6, montant_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, date_);
      }
      if (nuneroRadar_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, nuneroRadar_);
      }
      if (!getMatriculeVehiculeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, matriculeVehicule_);
      }
      if (vitesseMax_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, vitesseMax_);
      }
      if (montant_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, montant_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse)) {
        return super.equals(obj);
      }
      ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse other = (ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse) obj;

      if (getId()
          != other.getId()) return false;
      if (!getDate()
          .equals(other.getDate())) return false;
      if (getNuneroRadar()
          != other.getNuneroRadar()) return false;
      if (!getMatriculeVehicule()
          .equals(other.getMatriculeVehicule())) return false;
      if (java.lang.Double.doubleToLongBits(getVitesseMax())
          != java.lang.Double.doubleToLongBits(
              other.getVitesseMax())) return false;
      if (java.lang.Double.doubleToLongBits(getMontant())
          != java.lang.Double.doubleToLongBits(
              other.getMontant())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (37 * hash) + NUNERORADAR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNuneroRadar());
      hash = (37 * hash) + MATRICULEVEHICULE_FIELD_NUMBER;
      hash = (53 * hash) + getMatriculeVehicule().hashCode();
      hash = (37 * hash) + VITESSEMAX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVitesseMax()));
      hash = (37 * hash) + MONTANT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMontant()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code InfractionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:InfractionResponse)
        ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse.class, ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse.Builder.class);
      }

      // Construct using ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        date_ = "";

        nuneroRadar_ = 0L;

        matriculeVehicule_ = "";

        vitesseMax_ = 0D;

        montant_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.infractionservice.web.grpc.stub.InfractionSefvice.internal_static_InfractionResponse_descriptor;
      }

      @java.lang.Override
      public ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse getDefaultInstanceForType() {
        return ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse build() {
        ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse buildPartial() {
        ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse result = new ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse(this);
        result.id_ = id_;
        result.date_ = date_;
        result.nuneroRadar_ = nuneroRadar_;
        result.matriculeVehicule_ = matriculeVehicule_;
        result.vitesseMax_ = vitesseMax_;
        result.montant_ = montant_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse) {
          return mergeFrom((ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse other) {
        if (other == ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        if (other.getNuneroRadar() != 0L) {
          setNuneroRadar(other.getNuneroRadar());
        }
        if (!other.getMatriculeVehicule().isEmpty()) {
          matriculeVehicule_ = other.matriculeVehicule_;
          onChanged();
        }
        if (other.getVitesseMax() != 0D) {
          setVitesseMax(other.getVitesseMax());
        }
        if (other.getMontant() != 0D) {
          setMontant(other.getMontant());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>string date = 2;</code>
       * @return The date.
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string date = 2;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>string date = 2;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }

      private long nuneroRadar_ ;
      /**
       * <code>int64 nuneroRadar = 3;</code>
       * @return The nuneroRadar.
       */
      public long getNuneroRadar() {
        return nuneroRadar_;
      }
      /**
       * <code>int64 nuneroRadar = 3;</code>
       * @param value The nuneroRadar to set.
       * @return This builder for chaining.
       */
      public Builder setNuneroRadar(long value) {
        
        nuneroRadar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 nuneroRadar = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNuneroRadar() {
        
        nuneroRadar_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object matriculeVehicule_ = "";
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @return The matriculeVehicule.
       */
      public java.lang.String getMatriculeVehicule() {
        java.lang.Object ref = matriculeVehicule_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matriculeVehicule_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @return The bytes for matriculeVehicule.
       */
      public com.google.protobuf.ByteString
          getMatriculeVehiculeBytes() {
        java.lang.Object ref = matriculeVehicule_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matriculeVehicule_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @param value The matriculeVehicule to set.
       * @return This builder for chaining.
       */
      public Builder setMatriculeVehicule(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        matriculeVehicule_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMatriculeVehicule() {
        
        matriculeVehicule_ = getDefaultInstance().getMatriculeVehicule();
        onChanged();
        return this;
      }
      /**
       * <code>string matriculeVehicule = 4;</code>
       * @param value The bytes for matriculeVehicule to set.
       * @return This builder for chaining.
       */
      public Builder setMatriculeVehiculeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        matriculeVehicule_ = value;
        onChanged();
        return this;
      }

      private double vitesseMax_ ;
      /**
       * <code>double vitesseMax = 5;</code>
       * @return The vitesseMax.
       */
      public double getVitesseMax() {
        return vitesseMax_;
      }
      /**
       * <code>double vitesseMax = 5;</code>
       * @param value The vitesseMax to set.
       * @return This builder for chaining.
       */
      public Builder setVitesseMax(double value) {
        
        vitesseMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double vitesseMax = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearVitesseMax() {
        
        vitesseMax_ = 0D;
        onChanged();
        return this;
      }

      private double montant_ ;
      /**
       * <code>double montant = 6;</code>
       * @return The montant.
       */
      public double getMontant() {
        return montant_;
      }
      /**
       * <code>double montant = 6;</code>
       * @param value The montant to set.
       * @return This builder for chaining.
       */
      public Builder setMontant(double value) {
        
        montant_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double montant = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMontant() {
        
        montant_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:InfractionResponse)
    }

    // @@protoc_insertion_point(class_scope:InfractionResponse)
    private static final ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse();
    }

    public static ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InfractionResponse>
        PARSER = new com.google.protobuf.AbstractParser<InfractionResponse>() {
      @java.lang.Override
      public InfractionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InfractionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InfractionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InfractionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.infractionservice.web.grpc.stub.InfractionSefvice.InfractionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InfractionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InfractionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InfractionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_InfractionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027InfractionSefvice.proto\"v\n\021InfractionR" +
      "equest\022\017\n\007montant\030\001 \001(\001\022\014\n\004date\030\002 \001(\t\022\023\n" +
      "\013nuneroRadar\030\003 \001(\003\022\031\n\021matriculeVehicule\030" +
      "\004 \001(\t\022\022\n\nvitesseMax\030\005 \001(\001\"\203\001\n\022Infraction" +
      "Response\022\n\n\002id\030\001 \001(\003\022\014\n\004date\030\002 \001(\t\022\023\n\013nu" +
      "neroRadar\030\003 \001(\003\022\031\n\021matriculeVehicule\030\004 \001" +
      "(\t\022\022\n\nvitesseMax\030\005 \001(\001\022\017\n\007montant\030\006 \001(\0012" +
      "R\n\025InfractionGrpcService\0229\n\016saveInfracti" +
      "on\022\022.InfractionRequest\032\023.InfractionRespo" +
      "nseB$\n\"ma.infractionservice.web.grpc.stu" +
      "bb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_InfractionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_InfractionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InfractionRequest_descriptor,
        new java.lang.String[] { "Montant", "Date", "NuneroRadar", "MatriculeVehicule", "VitesseMax", });
    internal_static_InfractionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_InfractionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_InfractionResponse_descriptor,
        new java.lang.String[] { "Id", "Date", "NuneroRadar", "MatriculeVehicule", "VitesseMax", "Montant", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
