package ma.infractionservice.web.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-06-27T13:22:40.505+01:00
 * Generated source version: 4.0.0
 *
 */
@WebService(targetNamespace = "http://soap.web.infractionservice.ma/", name = "InfractionService")
@XmlSeeAlso({ObjectFactory.class})
public interface InfractionService {

    @WebMethod
    @RequestWrapper(localName = "updateInfraction", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.UpdateInfraction")
    @ResponseWrapper(localName = "updateInfractionResponse", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.UpdateInfractionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ma.infractionservice.web.soap.Infraction updateInfraction(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id,
        @WebParam(name = "infraction", targetNamespace = "")
        ma.infractionservice.web.soap.InfractionRequest infraction
    );

    @WebMethod
    @RequestWrapper(localName = "infractions", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.Infractions")
    @ResponseWrapper(localName = "infractionsResponse", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.InfractionsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ma.infractionservice.web.soap.Infraction> infractions()
;

    @WebMethod
    @RequestWrapper(localName = "deleteInfraction", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.DeleteInfraction")
    @ResponseWrapper(localName = "deleteInfractionResponse", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.DeleteInfractionResponse")
    public void deleteInfraction(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "infractionById", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.InfractionById")
    @ResponseWrapper(localName = "infractionByIdResponse", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.InfractionByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ma.infractionservice.web.soap.Infraction infractionById(

        @WebParam(name = "id", targetNamespace = "")
        java.lang.Long id
    );

    @WebMethod
    @RequestWrapper(localName = "saveInfraction", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.SaveInfraction")
    @ResponseWrapper(localName = "saveInfractionResponse", targetNamespace = "http://soap.web.infractionservice.ma/", className = "ma.infractionservice.web.soap.SaveInfractionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ma.infractionservice.web.soap.Infraction saveInfraction(

        @WebParam(name = "infraction", targetNamespace = "")
        ma.infractionservice.web.soap.InfractionRequest infraction
    );
}
