package ma.enset.immatriculationservice.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.0
 * 2023-06-27T13:19:48.422+01:00
 * Generated source version: 4.0.0
 *
 */
@WebServiceClient(name = "ImmatriculationSoapServiceService",
                  wsdlLocation = "file:/C:/Users/anaso/IdeaProjects/exam-s2/radar-service/src/main/resources/ImmatriculationService.wsdl",
                  targetNamespace = "http://soap.web.immatriculationservice.enset.ma/")
public class ImmatriculationSoapServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.web.immatriculationservice.enset.ma/", "ImmatriculationSoapServiceService");
    public final static QName ImmatriculationServicePort = new QName("http://soap.web.immatriculationservice.enset.ma/", "ImmatriculationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/anaso/IdeaProjects/exam-s2/radar-service/src/main/resources/ImmatriculationService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ImmatriculationSoapServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/anaso/IdeaProjects/exam-s2/radar-service/src/main/resources/ImmatriculationService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ImmatriculationSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ImmatriculationSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImmatriculationSoapServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ImmatriculationSoapServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ImmatriculationSoapServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ImmatriculationSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ImmatriculationService
     */
    @WebEndpoint(name = "ImmatriculationServicePort")
    public ImmatriculationService getImmatriculationServicePort() {
        return super.getPort(ImmatriculationServicePort, ImmatriculationService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImmatriculationService
     */
    @WebEndpoint(name = "ImmatriculationServicePort")
    public ImmatriculationService getImmatriculationServicePort(WebServiceFeature... features) {
        return super.getPort(ImmatriculationServicePort, ImmatriculationService.class, features);
    }

}
